[package]
name = "leetcode"
# don't change this, it's updated before an actual build by update-version.sh
version = "0.0.0-development"
edition = "2021"
rust-version = "1.80.1"
authors = ["Kristof Mattei"]
description = "Leetcode"
license-file = "LICENSE"
categories = ["playground"]
keywords = ["playground"]
repository = "https://github.com/kristof-mattei/leetcode"

[lib]
path = "src/lib.rs"
test = true
crate-type = ["lib"]

[profile.dev]
debug = true

[profile.release]
debug = true

[profile.bench]
debug = true

[profile.test]
debug = true

[lints.clippy]
# don't stop from compiling / running
all = "warn"
pedantic = "warn"
cargo = "warn"

# this one is WAY too buggy
assigning_clones = { level = "allow", priority = 127 }

# general things we don't care about when writing code for points
# as the input is narrowly defined
cast_possible_truncation = { level = "allow", priority = 127 }
cast_possible_wrap = { level = "allow", priority = 127 }
cast_sign_loss = { level = "allow", priority = 127 }

# easier debugging
let_and_return = { level = "allow", priority = 127 }

# yea, this one is debatable
too_many_lines = { level = "allow", priority = 127 }

# this one causes confusion when combining variables (`foo`) and
# dereferenced variables (`foo.bar`). The latter cannot be inlined
# so we don't inline anything
uninlined-format-args = { level = "allow", priority = 127 }

[lints.rust]
let_underscore_drop = { level = "deny", priority = 127 }
non_ascii_idents = { level = "deny", priority = 127 }

[profile.dev.package.backtrace]
opt-level = 3

[features]
coverage = []

[dev-dependencies]
cargo-husky = { version = "1.5.0", default-features = false, features = [
    "user-hooks",
] }

# We compile the Docker container with musl to get a static library. Smaller, faster.
# BUT that means that we need to include openssl
# Documentation on the syntax:
# https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies
[target.'cfg(all(target_arch = "x86_64", target_os="linux", target_env="musl"))'.dependencies]

[dependencies]
backtrace = "0.3.73"
# openssl = { version = "0.10.36", features = ["vendored"] }
